<a href="https://colab.research.google.com/github/chitrangada-juneja/CSC-380HWS/blob/Homeworks/CSC380_HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# code for Q5 calculations
#used SI Session 7 code as reference


import numpy as np
import scipy.stats as stats
# Step 1: Observed frequencies
observed = np.array([[18,26],[8,48]])
# Step 2: Perform chi-square test
chi2_stat, p_val, dof, expected = stats.chi2_contingency(observed)
# Step 3: Print the results
print("Observed Frequencies:")
print(observed)
print("\nExpected Frequencies:")
print(np.round(expected, 4))
print("\nChi-square Statistic:", round(chi2_stat, 4))
print("Degrees of Freedom:", dof)
print("P-value:", round(p_val, 4))
# Step 4: Check the critical value at 0.05 significance level
alpha = 0.05
critical_value = stats.chi2.ppf(1 - alpha, dof)
print("\nCritical Value at 0.05 significance level:", round(critical_value, 4))
# Step 5: Conclusion
if chi2_stat > critical_value:
  print("Reject the null hypothesis. There is a significant association between a person’s age and whether they actively use social media.")

else:
  print("Fail to reject the null hypothesis. There is no significant association between a person’s age and whether they actively use social media.")

Observed Frequencies:
[[18 26]
 [ 8 48]]

Expected Frequencies:
[[11.44 32.56]
 [14.56 41.44]]

Chi-square Statistic: 7.7464
Degrees of Freedom: 1
P-value: 0.0054

Critical Value at 0.05 significance level: 3.8415
Reject the null hypothesis. There is a significant association between a person’s age and whether they actively use social media.

Q6 TO 12

In [ ]:
import numpy as np
import pandas as pd



url = 'https://raw.githubusercontent.com/cpethe/TED_Talks/master/ted_main.csv'
ted_data = pd.read_csv(url)

############################

occupation_count=ted_data['speaker_occupation'].value_counts()
common_occupation=occupation_count.idxmax()
common_count=occupation_count.max()


print(f"The most common speaker occupation is '{common_occupation}' with {common_count} occurrences.")

##################################

# Drop the 'title' column
ted_data = ted_data.drop(columns=['name'])

ted_data.head()
###################################

The most common speaker occupation is 'Writer' with 45 occurrences.

,comments,description,duration,event,film_date,languages,main_speaker,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

In [ ]:
cc_in_descr = ted_data["description"].apply(lambda descr_str: "climate change" in descr_str)
ted_data[cc_in_descr]

,comments,description,duration,event,film_date,languages,main_speaker,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
109,295,"""I don't think we're going to make it,"" John D...",1072,TED2007,1172880000,20,John Doerr,1,1180266840,"[{'id': 3, 'name': 'Courageous', 'count': 174}...","[{'id': 192, 'hero': 'https://pe.tedcdn.com/im...",Venture capitalist,"['climate change', 'environment', 'global issu...",Salvation (and profit) in greentech,https://www.ted.com/talks/john_doerr_sees_salv...,805111
160,279,Environmental scientist David Keith proposes a...,958,TEDSalon 2007 Hot Science,1189296000,24,David Keith,1,1194918240,"[{'id': 8, 'name': 'Informative', 'count': 680...","[{'id': 193, 'hero': 'https://pe.tedcdn.com/im...",Environmental scientist,"['business', 'china', 'climate change', 'engin...",A critical look at geoengineering against clim...,https://www.ted.com/talks/david_keith_s_surpri...,876658
214,664,In this brand-new slideshow (premiering on TED...,1674,TED2008,1204502400,44,Al Gore,1,1207618020,"[{'id': 8, 'name': 'Informative', 'count': 105...","[{'id': 128, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['activism', 'climate change', 'global issues'...",New thinking on the climate crisis,https://www.ted.com/talks/al_gore_s_new_thinki...,1751426
491,514,"We're at a unique moment in history, says UK P...",1003,TEDGlobal 2009,1248134400,27,Gordon Brown,1,1248138000,"[{'id': 10, 'name': 'Inspiring', 'count': 711}...","[{'id': 700, 'hero': 'https://pe.tedcdn.com/im...",British Prime Minister,"['Europe', 'collaboration', 'communication', '...",Wiring a web for global good,https://www.ted.com/talks/gordon_brown\n,811914
504,99,"The wheat, corn and rice we grow today may not...",1028,TEDGlobal 2009,1248307200,26,Cary Fowler,1,1251680400,"[{'id': 25, 'name': 'OK', 'count': 74}, {'id':...","[{'id': 556, 'hero': 'https://pe.tedcdn.com/im...",Biodiversity archivist,"['Anthropocene', 'agriculture', 'biodiversity'...","One seed at a time, protecting the future of food",https://www.ted.com/talks/cary_fowler_one_seed...,679728
509,288,Photographer James Balog shares new image sequ...,1162,TEDGlobal 2009,1248307200,21,James Balog,1,1252371600,"[{'id': 24, 'name': 'Persuasive', 'count': 457...","[{'id': 89, 'hero': 'https://pe.tedcdn.com/ima...",Photographer,"['climate change', 'global issues', 'photograp...",Time-lapse proof of extreme ice loss,https://www.ted.com/talks/james_balog_time_lap...,914170
550,124,"In 4 minutes, atmospheric chemist Rachel Pike ...",253,TEDGlobal 2009,1248393600,31,Rachel Pike,1,1257843720,"[{'id': 22, 'name': 'Fascinating', 'count': 10...","[{'id': 594, 'hero': 'https://pe.tedcdn.com/im...",Atmospheric chemist,"['chemistry', 'climate change', 'environment',...",The science behind a climate headline,https://www.ted.com/talks/rachel_pike_the_scie...,470615
741,173,"After he swam the North Pole, Lewis Pugh vowed...",585,TEDGlobal 2010,1279152000,31,Lewis Pugh,1,1280480100,"[{'id': 26, 'name': 'Obnoxious', 'count': 42},...","[{'id': 629, 'hero': 'https://pe.tedcdn.com/im...",Coldwater swimmer,"['activism', 'adventure', 'climate change', 'g...",My mind-shifting Everest swim,https://www.ted.com/talks/lewis_pugh_s_mind_sh...,1029186
782,364,"As the world faces recession, climate change, ...",1223,TEDGlobal 2010,1279152000,28,Tim Jackson,1,1286270340,"[{'id': 26, 'name': 'Obnoxious', 'count': 32},...","[{'id': 62, 'hero': 'https://pe.tedcdn.com/ima...",Economist,"['economics', 'global development', 'green', '...",An economic reality check,https://www.ted.com/talks/tim_jackson_s_econom...,899942
1166,844,Top climate scientist James Hansen tells the s...,1071,TED2012,1330473600,30,James Hansen,1,1331136539,"[{'id': 1, 'name': 'Beautiful', 'count': 62}, ...","[{'id': 535, 'hero': 'https://pe.tedcdn.com/im...",Climatologist,"['big problems', 'climate change', 'environmen...",Why I must speak out about climate change,https://www.ted.com/talks/james_hansen_why_i_m...,1243930
1199,419,A skyrocketing demand for food means that agri...,1066,TEDxTC,1286928000,25,Jonathan Foley,1,1333893631,"[{'id': 8, 'name': 'Informative', 'count': 539...","[{'id': 1018, 'hero': 'https://pe.tedcdn.com/i...",Professor,"['TEDx', 'agriculture', 'environment', 'global...",The other inconvenient truth,https://www.ted.com/talks/jonathan_foley_the_o...,702977
1448,1586,"""Desertification is a fancy word for land that...",1339,TED2013,1362009600,33,Allan Savory,1,1362412271,"[{'id': 24, 'name': 'Persuasive', 'count': 114...","[{'id': 1018, 'hero': 'https://pe.tedcdn.com/i...",Grassland ecosystem pioneer,"['agriculture', 'climate change', 'green']",How to fight desertification and reverse clima...,https://www.ted.com/talks/allan_savory_how_to_...,4191678
1595,218,"Why do we turn to nonprofits, NGOs and governm...",988,TEDGlobal 2013,1371168000,29,Michael Porter,1,1381158304,"[{'id': 8, 'name': 'Informative', 'count': 252...","[{'id': 1836, 'hero': 'https://pe.tedcdn.com/i...",Business strategist,"['Debate', 'big problems', 'business', 'social...",The case for letting business solve social pro...,https://www.ted.com/talks/michael_porter_why_b...,1573620
1735,143,"You can't understand climate change in pieces,...",730,TED2014,1394582400,24,Gavin Schmidt,1,1398956538,"[{'id': 8, 'name': 'Informative', 'count': 510...","[{'id': 1, 'hero': 'https://pe.tedcdn.com/imag...",Climate scientist,"['algorithm', 'botany', 'climate change', 'cod...",The emergent patterns of climate change,https://www.ted.com/talks/gavin_schmidt_the_em...,1150409
1825,176,"How can we begin to address the global, insidi...",993,TED@Unilever,1410912000,23,Lord Nicholas Stern,1,1411397743,"[{'id': 11, 'name': 'Longwinded', 'count': 49}...","[{'id': 1380, 'hero': 'https://pe.tedcdn.com/i...",Climate economist,"['Anthropocene', 'business', 'climate change',...",The state of the climate — and what we might d...,https://www.ted.com/talks/lord_nicholas_stern_...,773801
1894,22,"""Save the rainforest"" is an environmental slog...",916,TEDGlobal 2014,1413417600,25,Tasso Azevedo,1,1420822220,"[{'id': 8, 'name': 'Informative', 'count': 214...","[{'id': 2075, 'hero': 'https://pe.tedcdn.com/i...",Forester and sustainability activist,"['climate change', 'conservation', 'ecology', ...",Hopeful lessons from the battle to save rainfo...,https://www.ted.com/talks/tasso_azevedo_hopefu...,877692
2063,76,"Can we end hunger and poverty, halt climate ch...",879,TEDGlobal>London,1443484800,32,Michael Green,1,1444665495,"[{'id': 8, 'name': 'Informative', 'count': 421...","[{'id': 2229, 'hero': 'https://pe.tedcdn.com/i...",Social progress expert,"['big problems', 'economics', 'future', 'globa...",How we can make the world a better place by 2030,https://www.ted.com/talks/michael_green_how_we...,1141254
2088,65,"For the people of Kiribati, climate change isn...",1275,Mission Blue II,1444435200,22,Anote Tong,1,1447861608,"[{'id': 26, 'name': 'Obnoxious', 'count': 11},...","[{'id': 998, 'hero': 'https://pe.tedcdn.com/im...",President of the Republic of Kiribati,"['big problems', 'climate change', 'environmen...",My country will be underwater soon -- unless w...,https://www.ted.com/talks/anote_tong_my_countr...,1054718
2113,43,As the world's climate patterns continue to sh...,817,TEDxMarin,1442448000,21,David Sedlak,1,1452184818,"[{'id': 8, 'name': 'Informative', 'count': 265...","[{'id': 2088, 'hero': 'https://pe.tedcdn.com/i...",Civil and environmental engineer,"['TEDx', 'chemistry', 'climate change', 'desig...",4 ways we can avoid a catastrophic drought,https://www.ted.com/talks/david_sedlak_4_ways_...,1013976
2119,25,Cave diver Jill Heinerth explores the hidden u...,409,TEDYouth 2015,1447459200,36,Jill Heinerth,1,1452874130,"[{'id': 8, 'name': 'Informative', 'count': 222...","[{'id': 2359, 'hero': 'https://pe.tedcdn.com/i...",Cave diver,"['TEDYouth', 'adventure', 'climate change', 'c...",The mysterious world of underwater caves,https://www.ted.com/talks/jill_heinerth_the_my...,1468644
2120,52,As the world's population grows and the effect...,836,TEDGlobal>Geneva,1449532800,25,Jill Farrant,1,1453220281,"[{'id': 1, 'name': 'Beautiful', 'count': 102},...","[{'id': 2065, 'hero': 'https://pe.tedcdn.com/i...",Professor of molecular and cell biology,"['Africa', 'Bioethics', 'agriculture', 'biolog...",How we can make crops survive without water,https://www.ted.com/talks/jill_farrant_how_we_...,1332162
2144,362,Why is Al Gore optimistic about climate change...,1520,TED2016,1455667200,27,Al Gore,1,1456157793,"[{'id': 1, 'name': 'Beautiful', 'count': 233},...","[{'id': 1583, 'hero': 'https://pe.tedcdn.com/i...",Climate advocate,"['alternative energy', 'climate change', 'ener...",The case for optimism on climate change,https://www.ted.com/talks/al_gore_the_case_for...,1624248
2181,140,"Hugh Evans started a movement that mobilizes ""...",1016,TED2016,1455667200,28,Hugh Evans,1,1460377474,"[{'id': 7, 'name': 'Funny', 'count': 45}, {'id...","[{'id': 2463, 'hero': 'https://pe.tedcdn.com/i...",Humanitarian,"['activism', 'big problems', 'climate change',...",What does it mean to be a citizen of the world?,https://www.ted.com/talks/hugh_evans_what_does...,1360404
2186,107,What would you do if your job was to save the ...,891,TED2016,1455667200,24,Christiana Figueres,1,1460991320,"[{'id': 1, 'name': 'Beautiful', 'count': 70}, ...","[{'id': 2331, 'hero': 'https://pe.tedcdn.com/i...",Climate advocate,"['alternative energy', 'big problems', 'climat...",The inside story of the Paris climate agreement,https://www.ted.com/talks/christiana_figueres_...,1031398
2195,40,Will we do whatever it takes to fight climate ...,772,TED@State Street Boston,1446508800,17,Michael Metcalfe,1,1461854801,"[{'id': 8, 'name': 'Informative', 'count': 166...","[{'id': 1929, 'hero': 'https://pe.tedcdn.com/i...",Financial expert,"['big problems', 'business', 'climate change',...",A provocative way to finance the fight against...,https://www.ted.com/talks/michael_metcalfe_a_p...,1184083
2256,56,"Our poop and pee have superpowers, but for the...",741,TEDxBend,1461369600,20,Molly Winter,1,1470840730,"[{'id': 9, 'name': 'Ingenious', 'count': 202},...","[{'id': 1713, 'hero': 'https://pe.tedcdn.com/i...",Designer,"['Natural resources', 'TEDx', 'activism', 'agr...",The taboo secret to better health,https://www.ted.com/talks/molly_winter_the_tab...,1507057
2449,15,Oceanographer Kate Stafford lowers us into the...,711,TEDxCERN,1478304000,15,Kate Stafford,1,1494601475,"[{'id': 8, 'name': 'Informative', 'count': 171...","[{'id': 886, 'hero': 'https://pe.tedcdn.com/im...",Oceanographer,"['Anthropocene', 'Senses', 'TEDx', 'animals', ...",How human noise affects ocean habitats,https://www.ted.com/talks/kate_stafford_how_hu...,975412
2461,33,As we keep pumping carbon dioxide into the atm...,543,TEDxFulbrightDublin,1454716800,21,Triona McGrath,1,1496070198,"[{'id': 8, 'name': 'Informative', 'count': 215...","[{'id': 2385, 'hero': 'https://pe.tedcdn.com/i...",Chemical oceanographer,"['TEDx', 'animals', 'biodiversity', 'biology',...",How pollution is changing the ocean's chemistry,https://www.ted.com/talks/triona_mcgrath_how_p...,1052652
2513,26,More than half of the world's population alrea...,860,TED2017,1492992000,4,Peter Calthorpe,1,1502981603,"[{'id': 8, 'name': 'Informative', 'count': 95}...","[{'id': 2609, 'hero': 'https://pe.tedcdn.com/i...",Urban designer,"['architecture', 'design', 'future', 'infrastr...",7 principles for building better cities,https://www.ted.com/talks/peter_calthorpe_7_pr...,834190

In [ ]:

filtered_talks = ted_data[(ted_data['views'] >= 10_000_000) | (ted_data['comments'] >= 3000)]
sorted_talks = filtered_talks.sort_values(by='duration', ascending=True)

top_10_longest_talks = sorted_talks.head(10)

print(top_10_longest_talks)

      comments                                        description  duration  \
47         578  Why do people succeed? Is it because they're s...       210
176        554  David Gallo shows jaw-dropping footage of amaz...       327
1501       659  Leaving a high-flying job in consulting, Angel...       372
1579       285  Hailed as the greatest pickpocket in the world...       527
1416       846  Cameron Russell admits she won “a genetic lott...       577
2114       150  Suspicious emails: unclaimed insurance bonds, ...       588
1776       297  Have you ever felt like you're talking, but no...       598
1129       754  We believe we should work hard in order to be ...       740
2109       527  What keeps us happy and healthy as we go throu...       766
553       1329  At TEDIndia, Pranav Mistry demos several tools...       830

                    event   film_date  languages          main_speaker  \
47                TED2005  1109116800         66      Richard St. John
176               TED2007  1172880000         47           David Gallo
1501  TED Talks Education  1365033600         49  Angela Lee Duckworth
1579       TEDGlobal 2013  1370995200         37        Apollo Robbins
1416      TEDxMidAtlantic  1351296000         43       Cameron Russell
2114     TEDGlobal>Geneva  1449532800         43          James Veitch
1776       TEDGlobal 2013  1370822400         45       Julian Treasure
1129      TEDxBloomington  1305072000         46           Shawn Achor
2109     TEDxBeaconStreet  1447459200         43      Robert Waldinger
553         TEDIndia 2009  1257379200         42         Pranav Mistry

      num_speaker  published_date  \
47              1      1166055060
176             1      1200011280
1501            1      1368111588
1579            1      1379084559
1416            1      1358352354
2114            1      1452269020
1776            1      1403879897
1129            1      1328112578
2109            1      1450889841
553             1      1258333200

                                                ratings  \
47    [{'id': 7, 'name': 'Funny', 'count': 2966}, {'...
176   [{'id': 23, 'name': 'Jaw-dropping', 'count': 8...
1501  [{'id': 10, 'name': 'Inspiring', 'count': 4847...
1579  [{'id': 24, 'name': 'Persuasive', 'count': 418...
1416  [{'id': 11, 'name': 'Longwinded', 'count': 92}...
2114  [{'id': 7, 'name': 'Funny', 'count': 7731}, {'...
1776  [{'id': 24, 'name': 'Persuasive', 'count': 267...
1129  [{'id': 10, 'name': 'Inspiring', 'count': 1121...
2109  [{'id': 10, 'name': 'Inspiring', 'count': 8590...
553   [{'id': 23, 'name': 'Jaw-dropping', 'count': 8...

                                          related_talks  \
47    [{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...
176   [{'id': 77, 'hero': 'https://pe.tedcdn.com/ima...
1501  [{'id': 1289, 'hero': 'https://pe.tedcdn.com/i...
1579  [{'id': 1496, 'hero': 'https://pe.tedcdn.com/i...
1416  [{'id': 1438, 'hero': 'https://pe.tedcdn.com/i...
2114  [{'id': 2236, 'hero': 'https://pe.tedcdn.com/i...
1776  [{'id': 1200, 'hero': 'https://pe.tedcdn.com/i...
1129  [{'id': 366, 'hero': 'https://pe.tedcdn.com/im...
2109  [{'id': 1669, 'hero': 'https://pe.tedcdn.com/i...
553   [{'id': 481, 'hero': 'https://pe.tedcdn.com/im...

                                  speaker_occupation  \
47                         Marketer, success analyst
176                                    Oceanographer
1501                                    Psychologist
1579                                 Gentleman thief
1416                                           Model
2114                             Comedian and writer
1776                                Sound consultant
1129                                    Psychologist
2109      Psychiatrist, psychoanalyst and Zen priest
553   Director of research, Samsung Research America

                                                   tags  \
47    ['business', 'culture', 'entertainment', 'happ...
176   ['animals', 'evolution', 'exploration', 'fish'...
1501  ['business', 'education', 'psychology', 'succe...
1579                         ['crime', 'entertainment']
1416  ['TEDx', 'beauty', 'culture', 'fashion', 'phot...
2114  ['comedy', 'communication', 'curiosity', 'humo...
1776                     ['culture', 'sound', 'speech']
1129  ['TEDx', 'brain', 'business', 'cognitive scien...
2109  ['TEDx', 'aging', 'data', 'friendship', 'happi...
553     ['demo', 'design', 'open-source', 'technology']

                                                  title  \
47                                 8 secrets of success
176                            Underwater astonishments
1501        Grit: The power of passion and perseverance
1579                            The art of misdirection
1416  Looks aren't everything. Believe me, I'm a model.
2114  This is what happens when you reply to spam email
1776         How to speak so that people want to listen
1129                    The happy secret to better work
2109  What makes a good life? Lessons from the longe...
553    The thrilling potential of SixthSense technology

                                                    url     views
47    https://www.ted.com/talks/richard_st_john_s_8_...  10841210
176   https://www.ted.com/talks/david_gallo_shows_un...  13926113
1501  https://www.ted.com/talks/angela_lee_duckworth...  12039978
1579  https://www.ted.com/talks/apollo_robbins_the_a...  15283242
1416  https://www.ted.com/talks/cameron_russell_look...  19787465
2114  https://www.ted.com/talks/james_veitch_this_is...  20475972
1776  https://www.ted.com/talks/julian_treasure_how_...  21594632
1129  https://www.ted.com/talks/shawn_achor_the_happ...  16209727
2109  https://www.ted.com/talks/robert_waldinger_wha...  16601927
553   https://www.ted.com/talks/pranav_mistry_the_th...  16097077

In [32]:
from ast import literal_eval


# Initialize variables to track the talk with the max difference in views
max_diff_talk = None
max_diff_value = 0

# Iterate through each row to calculate view differences
for index, row in ted_data.iterrows():

    if pd.notna(row['related_talks']):
        related_talks = literal_eval(row['related_talks'])


        # Calculate the view difference for each related talk
        for related in related_talks:

            view_difference = abs(row['views'] - related['viewed_count'])

            # Check if this is the maximum difference encountered
            # if not, we switch it to curr
            if view_difference > max_diff_value:
                max_diff_value = view_difference
                max_diff_talk = row

# Display the talk with the largest view difference
print("Talk with the maximum view difference compared to related talks:")
print(max_diff_talk[['title']])
print(f"Maximum difference in views: {max_diff_value}")

Talk with the maximum view difference compared to related talks:
title    "Put the financial aid in the bag"
Name: 1198, dtype: object
Maximum difference in views: 47042958

In [ ]:
# Select only numeric columns for correlation
numeric_columns = ted_data.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_columns.corr()
#now, we convert the 2-d into a 1-d version to make it easier to compute further
correlation_pairs = correlation_matrix.unstack()
sorted_pairs = correlation_pairs.sort_values(ascending=False) # sorting

#we have self-pairs with a correlation of 1 , so we get rid of those
sorted_pairs = sorted_pairs[sorted_pairs < 1]

#getting max
# Get the most correlated pair
most_correlated = sorted_pairs.idxmax()
most_correlated_value = sorted_pairs.max()
print(f"Most correlated Features: {most_correlated}, Correlation: {most_correlated_value}")

Most correlated Features: ('film_date', 'published_date'), Correlation: 0.902564558725761

In [31]:
#The p-value indicates the probability that the observed correlation is due to chance.
#the Pearson correlation test, which provides both the correlation coefficient and a p-value, is a good one because
# The p-value indicates whether the observed correlation is statistically significant, depending on the
# t statistic used
# this can help us understand the correlation between the elements of the csv being assessed
from scipy.stats import pearsonr

# Drop rows with missing values in 'duration' or 'comments'
ted_data = ted_data.dropna(subset=['duration', 'comments'])
# Calculate the Pearson correlation coefficient and p-value
correlation_coefficient, p_value = pearsonr(ted_data['duration'], ted_data['comments'])

#f strings to display our found correlation
print(f"Correlation Coefficient: {correlation_coefficient}")
print(f"P-Value: {(p_value)}")

Correlation Coefficient: 0.14069364760321115
P-Value: 9.55828468975491e-13